- hosts: all
  vars_files:
  - vars/{{ ansible_facts['distribution'] }}.yml

  tasks:
  - name: "Installing Software"
    package:
        name: "{{ software_name }}"
        state: present

  - name: "Copying Webpage"
    copy:
        src: files/{{ ansible_facts['distribution'] }}.html
        dest: "/var/www/html/"

  - name: "Starting Service"
    service:
        name: "{{ software_name }}"
        state: started
